pdp/forum/urls.py
# coding: utf-8
#
# This file is part of Progdupeupl.
#
# Progdupeupl is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Progdupeupl is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Progdupeupl. If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, url

from pdp.forum import views
from pdp.forum import feeds

urlpatterns = patterns(
    '',

    # Feeds
    url(r'^flux/rss/$', views.deprecated_feed_messages_rss),
    url(r'^flux/atom/$', views.deprecated_feed_messages_atom),

    url(r'^flux/messages/rss/$', feeds.LastPostsFeedRSS(),
        name='post-feed-rss'),
    url(r'^flux/messages/atom/$', feeds.LastPostsFeedATOM(),
        name='post-feed-atom'),

    url(r'^flux/sujets/rss/$', feeds.LastTopicsFeedRSS(),
        name='topic-feed-rss'),
    url(r'^flux/sujets/atom/$', feeds.LastTopicsFeedATOM(),
        name='topic-feed-atom'),

    # Deprecated URLs, have to be checked before new ones to avoid conflict
    url(r'^sujet/(?P<topic_pk>\d+)-(?P<topic_slug>.+)$',
        views.deprecated_topic_redirect),
    url(r'^(?P<cat_slug>.+)/(?P<forum_pk>\d+)-(?P<forum_slug>.+)/$',
        views.deprecated_details_redirect),
    url(r'^(?P<cat_pk>\d+)-(?P<cat_slug>.+)/$',
        views.deprecated_cat_details_redirect),

    # Viewing a thread
    url(r'^sujet/nouveau$', views.new),
    url(r'^sujet/editer$', views.edit),
    url(r'^sujet/(?P<topic_pk>\d+)/(?P<topic_slug>.+)$', views.topic),
    url(r'^sujets/(?P<name>.+)', views.find_topic),

    # Message-related
    url(r'^message/editer$', views.edit_post),
    url(r'^message/nouveau$', views.answer),
    url(r'^message/utile$', views.useful_post),
    url(r'^messages/(?P<name>.+)$', views.find_post),

    # Forum details
    url(r'^(?P<cat_slug>.+)/(?P<forum_slug>.+)/$',
        views.details),

    # Forums belonging to one category
    url(r'^(?P<cat_slug>.+)/$', views.cat_details),

    # Home
    url(r'^$', views.index),

    # Followed topics
    url(r'^suivis$', views.followed_topics),
)

pdp/urls.py
# coding: utf-8
#
# This file is part of Progdupeupl.
#
# Progdupeupl is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Progdupeupl is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Progdupeupl. If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.auth.models import User, Group

from haystack.views import SearchView
from haystack.forms import ModelSearchForm

from rest_framework import viewsets, routers

from django.contrib import admin
admin.autodiscover()

import pdp.pages.views
import pdp.settings

# ViewSets define the view behavior.

class UserViewSet(viewsets.ModelViewSet):
    model = User


class GroupViewSet(viewsets.ModelViewSet):
    model = Group


# Routers provide an easy way of automatically determining the URL conf
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)

urlpatterns = patterns(
    '',

    url(r'^articles/', include('pdp.article.urls')),
    url(r'^tutoriels/', include('pdp.tutorial.urls')),
    url(r'^forums/', include('pdp.forum.urls')),
    url(r'^messages/', include('pdp.messages.urls')),
    url(r'^membres/', include('pdp.member.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pages/', include('pdp.pages.urls')),
    url(r'^galerie/', include('pdp.gallery.urls')),
    url(r'^api/', include('pdp.api.urls')),

    url(r'^$', pdp.pages.views.home),

    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
    url(r'^api-docs/', include('rest_framework_swagger.urls')),
    url(r'^oauth2/', include('provider.oauth2.urls', namespace='oauth2')),

    url(r'^recherche/', SearchView(
        template='search/search.html',
        form_class=ModelSearchForm),
        name='haystack_search'),

    url(r'^robots\.txt$', pdp.pages.views.robots),

) + static(pdp.settings.MEDIA_URL, document_root=pdp.settings.MEDIA_ROOT)

# Serve debug toolbar files on debug
if pdp.settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)))

# Make Django serve the files if needed (local versions)
if pdp.settings.SERVE:
    urlpatterns += patterns(
        '',

        # Static content for website assets
        (r'^static/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': pdp.settings.STATIC_ROOT}),

        # User-uploaded content
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': pdp.settings.MEDIA_ROOT}),
    )

pdp/forum/models.py
# coding: utf-8
#
# This file is part of Progdupeupl.
#
# Progdupeupl is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Progdupeupl is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Progdupeupl. If not, see <http://www.gnu.org/licenses/>.

"""Models for forum app."""

from math import ceil

from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

from pdp.utils import get_current_user
from pdp.utils.cache import template_cache_delete


class Category(models.Model):

    """A category, containing forums."""

    class Meta:
        verbose_name = u'Catégorie'
        verbose_name_plural = u'Catégories'

    title = models.CharField(u'Titre', max_length=80)
    position = models.IntegerField(u'Position', null=True, blank=True)
    slug = models.SlugField(max_length=80)

    def __unicode__(self):
        """Textual representation of a category.

        Returns:
            string

        """
        return self.title

    def get_absolute_url(self):
        """Get URL to view the category.

        Returns:
            string

        """
        return u'/forums/{0}/'.format(self.slug)

    def get_forums(self):
        """Retreive all forums owned by the category.

        Returns:
            QuerySet on Forum objects

        """
        return Forum.objects.all()\
            .filter(category=self)\
            .order_by('position_in_category')


class Forum(models.Model):

    """A forum, containing topics."""

    class Meta:
        verbose_name = u'Forum'
        verbose_name_plural = u'Forums'

    title = models.CharField(u'Titre', max_length=80)
    subtitle = models.CharField(u'Sous-titre', max_length=200, blank=True)

    category = models.ForeignKey(Category, verbose_name=u'Catégorie')
    position_in_category = models.IntegerField(u'Position dans la catégorie',
                                               null=True, blank=True)

    slug = models.SlugField(max_length=80)

    def __unicode__(self):
        """Textual representation of a forum.

        Returns:
            string

        """
        return self.title

    def get_absolute_url(self):
        """Get URL to view the forum.

        Returns:
            string

        """
        return u'/forums/{0}/{1}/'.format(
            self.category.slug,
            self.slug,
        )

    def get_topic_count(self):
        """Get the number of threads in the forum.

        Returns:
            QuerySet on integer

        """
        return Topic.objects.all().filter(forum__pk=self.pk).count()

    def get_post_count(self):
        """Get the number of posts in the forum.

        Returns:
            QuerySet on integer

        """
        return Post.objects.all().filter(topic__forum=self).count()

    def get_last_message(self):
        """Get the last message on the forum, if any.

        Returns:
            Post object or None

        """
        try:
            return Post.objects.all()\
                .filter(topic__forum__pk=self.pk)\
                .order_by('-pubdate')[0]
        except IndexError:
            return None

    def is_read(self):
        """Check if this forum was read by current user.

        For convenience for new users, we only mark the forum as unread if the
        user has not read messages posted after the datetime he joined.

        Returns:
            boolean

        """
        user = get_current_user()

        # Though the never_read func will return false for old topics, better
        # filter these old topics here so our topic set is way more compact
        # than a Topic.objects.all() on which we call never_read in for loop.
        topics = Topic.objects.all() \
            .filter(forum=self) \
            .filter(last_message__pubdate__gt=user.date_joined)

        for t in topics:
            if never_read(t):
                return False

        return True


class Topic(models.Model):

    """A thread, containing posts."""

    class Meta:
        verbose_name = u'Sujet'
        verbose_name_plural = u'Sujets'

    title = models.CharField(u'Titre', max_length=80)
    subtitle = models.CharField(u'Sous-titre', max_length=200, blank=True)

    forum = models.ForeignKey(Forum, verbose_name=u'Forum')
    author = models.ForeignKey(User, verbose_name=u'Auteur',
                               related_name='topics')
    last_message = models.ForeignKey('Post', null=True,
                                     related_name='last_message',
                                     verbose_name=u'Dernier message')
    pubdate = models.DateTimeField(u'Date de création', auto_now_add=True)

    is_solved = models.BooleanField(u'Est résolu', default=False)
    is_locked = models.BooleanField(u'Est verrouillé', default=False)
    is_sticky = models.BooleanField(u'Est en post-it', default=False)

    def __unicode__(self):
        """Textual representation of a topic.

        Returns:
            string

        """
        return self.title

    def get_absolute_url(self):
        """Get URL to view the topic.

        Returns:
            string

        """
        return u'/forums/sujet/{0}/{1}'.format(self.pk, slugify(self.title))

    def get_post_count(self):
        """Return the number of posts in the topic.

        Returns:
            QuerySet on integer

        """
        return Post.objects.all().filter(topic__pk=self.pk).count()

    def get_last_answer(self):
        """Gets the last answer in the thread, if any.

        Returns:
            Post object or None

        """
        try:
            last_post = Post.objects.all()\
                .filter(topic__pk=self.pk)\
                .order_by('-pubdate')[0]
        except IndexError:
            return None

        # We do not want first post to be considered as an answer.
        if last_post == self.first_post():
            return None
        else:
            return last_post

    def first_post(self):
        """Return the first post of a topic, written by topic's author.

        Returns:
            Post object or None

        """
        try:
            return Post.objects\
                .filter(topic=self)\
                .order_by('pubdate')[0]
        except IndexError:
            return None

    def last_read_post(self):
        """Return the last post the user has read.

        Returns:
            Post object or None

        """
        user = get_current_user()

        if user is not None:
            # Logged-in user, so he may have a TopicRead instance
            try:
                return TopicRead.objects\
                    .select_related()\
                    .filter(topic=self, user=user)\
                    .latest('post__pubdate').post
            except TopicRead.DoesNotExist:
                return self.first_post()

        # Anonymous user, we return the last post since the first one is
        # available using the topic title link so it would have been redundant.
        resp = self.get_last_answer()
        return resp if resp is not None else self.first_post()

    def is_followed(self, user=None):
        """Check if the topic is currently followed by the user.

        This method uses the TopicFollowed objects.

        Returns:
            boolean

        """
        if user is None:
            user = get_current_user()

        try:
            TopicFollowed.objects.get(topic=self, user=user)
        except TopicFollowed.DoesNotExist:
            return False
        return True

    def antispam(self, user=None):
        """Check if the user is allowed to post in a topic.

        This method uses the SPAM_LIMIT_SECONDS value. If user shouldn't be
        able to post, then antispam is activated and this method returns True.
        Otherwise time elapsed between user's last post and now is enough, and
        the method will return False.

        Returns:
            boolean

        """
        if user is None:
            user = get_current_user()

        last_user_posts = Post.objects\
            .filter(topic=self)\
            .filter(author=user)\
            .order_by('-pubdate')

        if last_user_posts and last_user_posts[0] == self.get_last_answer():
            last_user_post = last_user_posts[0]
            t = timezone.now() - last_user_post.pubdate
            if t.total_seconds() < settings.SPAM_LIMIT_SECONDS:
                return True

        return False

    def never_read(self):
        return never_read(self)


class Post(models.Model):

    """A forum post written by an user."""

    topic = models.ForeignKey(Topic, verbose_name=u'Sujet')
    author = models.ForeignKey(User, verbose_name=u'Auteur',
                               related_name='posts')
    text = models.TextField(u'Texte')

    pubdate = models.DateTimeField(u'Date de publication', auto_now_add=True)
    update = models.DateTimeField(u'Date d\'édition', null=True, blank=True)

    position_in_topic = models.IntegerField(u'Position dans le sujet')

    is_useful = models.BooleanField(u'Est utile', default=False)

    def __unicode__(self):
        """Textual representation of a post.

        Returns:
            string

        """
        return u'<Post pour "{0}", #{1}>'.format(self.topic, self.pk)

    def get_absolute_url(self):
        """Get URL to view the post.

        Returns:
            string

        """
        page = int(ceil(

pdp/forum/forms.py
# coding: utf-8
#
# This file is part of Progdupeupl.
#
# Progdupeupl is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Progdupeupl is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Progdupeupl. If not, see <http://www.gnu.org/licenses/>.

from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div

from crispy_forms_foundation.layout import Layout, Submit, HTML, Field


class TopicForm(forms.Form):
    title = forms.CharField(
        label=u'Titre',
        max_length=80,
        widget=forms.TextInput(attrs={'autofocus': 'autofocus'})
    )

    subtitle = forms.CharField(
        label=u'Sous-titre',
        max_length=255,
        required=False
    )

    text = forms.CharField(
        label=u'Texte',
        widget=forms.Textarea
    )

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.helper.layout = Layout(
            Field('title'),
            Field('subtitle',
                  placeholder=u'Facultatif, permet de mieux décrire votre '
                              u'sujet.'),
            HTML('{% include "misc/editor.part.html" %}'),
            Field('text',
                  placeholder=u'Contenu de votre message au format Markdown.'),
            Div(
                Submit('submit', u'Créer le sujet'),
                Submit('preview', u'Prévisualiser', css_class='secondary'),
                HTML(u'<a href="{{ forum.get_absolute_url }}" class="button '
                     u'secondary">Retour</a>'),
                css_class='button-center'
            )
        )
        super(TopicForm, self).__init__(*args, **kwargs)


class PostForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea)

templates/forum/answer.html
{% extends "forum/base.html" %}
{% block title %}
    Répondre au sujet
{% endblock %}

{% block headline %}
    Répondre au sujet
{% endblock %}

{% block headline-sub %}
    {{ topic.title }}
{% endblock %}

{% block breadcrumb %}
    <li><a href="{{ topic.forum.category.get_absolute_url }}">{{ topic.forum.category.title }}</a></li>
    <li><a href="{{ topic.forum.get_absolute_url }}">{{ topic.forum.title }}</a></li>
    <li><a href="{{ topic.get_absolute_url }}">{{ topic.title }}</a></li>
    <li class="current"><a href="javascript:;">Répondre au sujet</a></li>
{% endblock %}

{% block content %}

{% if newpost %}
<div class="row">
    <div class="large-12 columns">
        <div class="alert-box alert">
            <strong>Au moins un nouveau message a été posté</strong> dans la
            discussion pendant que vous rédigiez le votre.
        </div>
    </div>
</div>
{% endif %}

{% include "misc/editor.part.html" %}

<div class="row">
    <div class="large-12 columns">
        <form action="#previsualisation" method="POST">
            <textarea class="input-block-level" name="text" rows="20" id="id_text"
                placeholder="Contenu de votre message au format Markdown.">{{ text }}</textarea>

            <div style="text-align: center;">
                <button type="submit" class="button">
                    Répondre
                </button>

                <button type="submit" name="preview" class="button secondary">
                    Prévisualisation
                </button>

                <a href="{{ topic.get_absolute_url }}" class="button secondary">
                    Annuler
                </a>
            </div>

            <input type="hidden" name="last_post" value="{{ last_post_pk }}" />
            {% csrf_token %}
        </form>
    </div>
</div>

{% if text %}
    {% include "forum/previsualization.part.html" %}
{% endif %}

{% endblock %}

templates/forum/base.html
{% extends "base.html" %}

{% block title_base %}
    &#183; Forums
{% endblock %}

{% block breadcrumb_base %}
    <li><a href="{% url "pdp.forum.views.index" %}">Forums</a></li>
{% endblock %}

{% block menu_forum %}
    class="active"
{% endblock %}

templates/forum/cat_details.html
{% extends "forum/base.html" %}

{% block title %}
    {{ category.title }}
{% endblock %}

{% block headline %}
    {{ category.title }}
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="javascript:;">{{ category.title }}</a></li>
{% endblock %}

{% block content %}
    
{% include "forum/forums_common.part.html" %}

{% endblock %}

templates/forum/details_row.part.html
{% load humanize %}

<div class="forum-entry
    {% if topic.is_locked %}
        forum-entry-locked
    {% else %}
        {% if topic.is_solved %}
        forum-entry-solved
        {% endif %}
    {% endif %}">
    <div class="forum-entry-title
    {% if user.is_authenticated %}
        {% if topic.never_read %}
            unread
        {% endif %}
    {% endif %}">
        <h3>
            <a href="{{ topic.get_absolute_url }}">
                {{ topic.title }}
            </a>
        </h3>
        {% if topic.subtitle %}
            <p>
                {{ topic.subtitle }}
            </p>
        {% endif %}
    </div>
    <div class="forum-entry-count">
        <span class="label">
            {{ topic.get_post_count|add:"-1" }}
        </span>
    </div>
    <div class="forum-entry-desc">
        <p>
            {% with member=topic.author %}
                Par {% include "member/member_item_common.part.html" %}
            {% endwith %}
            <br />
            {% with answer=topic.get_last_answer %}
                {% if answer %}
                    Dernière rép.
                    <a href="{{ answer.get_absolute_url }}">
                        {% with date=answer.pubdate|naturaltime %}
                            {{ date }}
                        {% endwith %}
                    </a>
                    par
                    {% with member=answer.author %}
                        {% include "member/member_item_common.part.html" %}
                    {% endwith %}
                {% else %}
                    Aucune réponse
                {% endif %}
            {% endwith %}

        </p>
    </div>
</div>

templates/forum/edit_post.html
{% extends "forum/base.html" %}

{% block title %}
    Éditer un message
{% endblock %}

{% block headline %}
    Éditer un message
{% endblock %}

{% block breadcrumb %}
    <li><a href="{{ post.topic.forum.category.get_absolute_url }}">{{ post.topic.forum.category.title }}</a></li>
    <li><a href="{{ post.topic.forum.get_absolute_url }}">{{ post.topic.forum.title }}</a></li>
    <li><a href="{{ post.topic.get_absolute_url }}">{{ post.topic.title }}</a></li>
    <li class="current"><a href="javascript:;">Éditer un message</a></li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="large-12 columns">
        <form action="#previsualisation" method="POST">
            {% if topic %}
            <fieldset>
                <legend>Sujet</legend>
                <div class="control-group">
                    <label class="control-label" for="id_title">Titre</label>
                    <div class="controls">
                        <input type="text" name="title" id="id_title"
                            class="input-xxlarge" value="{{ topic.title }}" />
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="id_subtitle">Sous titre</label>
                    <div class="controls">
                        <input type="text" name="subtitle" id="id_subtitle"
                            class="input-xxlarge" value="{{ topic.subtitle }}" />
                    </div>
                </div>
            </fieldset>
            {% endif %}
            {% include "misc/editor.part.html" %}
            <fieldset>
                <legend>Message</legend>
                <div class="control-group">
                    <label class="control-label" for="id_text">Texte</label>
                    <div class="controls">
                        <textarea id="id_text" name="text"
                            class="input-block-level" rows="20">{{ text }}</textarea>
                    </div>
                </div>
            </fieldset>

            <div style="text-align: center;">
                <button type="submit" class="button">
                    Éditer
                </button>

                <button type="submit" name="preview" class="button secondary">
                    Prévisualisation
                </button>

                <a href="{{ post.get_absolute_url }}" class="button secondary">Annuler</a>
            </div>

            {% csrf_token %}
        </form>
    </div>
</div>

{% include "forum/previsualization.part.html" %}

{% endblock %}

templates/forum/feeds.part.html
<a href="#" class="button secondary dropdown" data-dropdown="forums-drop-feeds">
    S’abonner
</a><br />
<ul id="forums-drop-feeds" class="f-dropdown">
    <li><a href="{% url "post-feed-rss" %}">Nouveaux messages (RSS)</a></li>
    <li><a href="{% url "post-feed-atom" %}">Nouveaux messages (ATOM)</a></li>
    <li><a href="{% url "topic-feed-rss" %}">Nouveaux sujets (RSS)</a></li>
    <li><a href="{% url "topic-feed-atom" %}">Nouveaux sujets (ATOM)</a></li>
</ul>

templates/forum/find_post.html
{% extends "forum/base.html" %}
{% load humanize %}
{% load profile %}
{% load emarkdown %}

{% block title %}
    Messages postés par {{ usr.username }}
{% endblock %}

{% block headline %}
    Messages postés par {{ usr.username }}
{% endblock %}

{% block breadcrumb %}
    {% with profile=usr|profile %}
        <li ><a href="{{ profile.get_absolute_url }}">{{ usr.username }}</a></li>
    {% endwith %}
    <li ><a href="{% url "pdp.forum.views.find_post" usr.username %}">Messages postés</a></li>
    <li class="current"><a href="#">Recherche</a></li>
{% endblock %}

{% block content %}
{% include "misc/pagination.part.html" with position="top" %}
    <div class="row">
        <table>
          <thead>
            <tr>
              <th width="15%">Sujet</th>
              <th width="10%">Quand</th>
              <th width="30%">Extrait</th>
            </tr>
          </thead>
          <tbody>
            {% for post in posts %}
            <tr>
                <td>
                    <div class="forum-entry-title {% if user.is_authenticated %} {% if topic.never_read %} unread {% endif %} {% endif %}">
                        <a href="{{ post.get_absolute_url }}">{{ post.topic.title }} </a>
                        {% if post.topic.subtitle %} <p> {{ post.topic.subtitle }} </p> {% endif %}
                    </div>
                </td>
                <td>
                    {% with date=post.pubdate|naturaltime %}
                        {{ date }}
                    {% endwith %}
                </td>
                <td>
                    {{ post.text|truncatechars:200|emarkdown }}
                </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>

{% include "misc/pagination.part.html" with position="bottom" %}

{% endblock %}

templates/forum/find_topic.html
{% extends "forum/base.html" %}
{% load humanize %}
{% load profile %}
{% load emarkdown %}

{% block title %}
    Sujets créés par {{ usr.username }}
{% endblock %}

{% block headline %}
    Sujets créés par {{ usr.username }}
{% endblock %}

{% block breadcrumb %}
    {% with profile=usr|profile %}
        <li ><a href="{{ profile.get_absolute_url }}">{{ usr.username }}</a></li>
    {% endwith %}
    <li ><a href="{% url "pdp.forum.views.find_topic" usr.username %}">Sujets créés</a></li>
    <li class="current"><a href="#">Recherche</a></li>
{% endblock %}

{% block content %}
{% include "misc/pagination.part.html" with position="top" %}
    <div class="row">
        <table>
          <thead>
            <tr>
              <th width="15%">Sujet</th>
              <th width="10%">Quand</th>
              <th width="30%">Extrait</th>
            </tr>
          </thead>
          <tbody>
            {% for topic in topics %}
            <tr>
                <td>
                    <div class="forum-entry-title {% if user.is_authenticated %} {% if topic.never_read %} unread {% endif %} {% endif %}">
                        <a href="{{ topic.get_absolute_url }}">{{ topic.title }} </a> 
                        {% if topic.subtitle %} <p> {{ topic.subtitle }} </p> {% endif %}
                    </div>
                </td>
                <td>
                    {% with date=topic.pubdate|naturaltime %}
                        {{ date }}
                    {% endwith %}
                </td>
                <td>
                    {{ topic.first_post.text|truncatechars:200|emarkdown }}
                </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>

{% include "misc/pagination.part.html" with position="bottom" %}

{% endblock %}

templates/forum/forums_common.part.html
{# Block displaying the list of forums belonging to a category #}
{% load humanize %}

{% with forums=category.get_forums %}
{% if forums %}
{% for forum in forums %}
<div class="forum-entry">
    <div class="forum-entry-title {% if user.is_authenticated and not forum.is_read %}unread{% endif %}">
        <h3>
            <a href="{% url "pdp.forum.views.details" cat_slug=category.slug forum_slug=forum.slug %}">
                {{ forum.title }}
            </a>
        </h3>
        <p>
            {{ forum.subtitle }}
        </p>
    </div>
    <div class="forum-entry-count">
        <span class="label">
            <span title="Nombre de sujets dans le forum">
                {{ forum.get_topic_count }}
            </span>
        </span>
        <span class="label secondary">
            <span title="Nombre de messages dans le forum">
                {{ forum.get_post_count }}
            </span>
        </span>
    </div>
    <div class="forum-entry-desc">
        <p>
            {% with last_message=forum.get_last_message %}
                {% if last_message %}
                    <a href="{{ last_message.get_absolute_url }}">
                        {% with date=last_message.pubdate|naturaltime %}
                            {{ date|capfirst }}
                        {% endwith %}
                    </a>
                    par
                    {% with member=last_message.author %}
                        {% include "member/member_item_common.part.html" %}
                    {% endwith %}
                    dans
                    <a href="{{ last_message.topic.get_absolute_url }}">
                        {{ last_message.topic.title }}
                    </a>
                {% else %}
                    Aucun message
                {% endif %}
            {% endwith %}
        </p>
    </div>
</div>
{% endfor %}
{% else %}
    <div class="row">
        <div class="large-12 columns">
            <p>Aucun forum dans cette catégorie.</p>
        </div>
    </div>
{% endif %}
{% endwith %}

templates/forum/new.html
{% extends "forum/base.html" %}
{% load emarkdown %}
{% load crispy_forms_tags %}

{% block title %}
    Nouveau sujet
{% endblock %}

{% block headline %}
    Nouveau sujet
{% endblock %}

{% block breadcrumb %}
    <li><a href="{{ forum.category.get_absolute_url }}">{{ forum.category.title }}</a></li>
    <li><a href="{{ forum.get_absolute_url }}">{{ forum.title }}</a></li>
    <li class="current"><a href="javascript:;">Nouveau sujet</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        {% crispy form %}
    </div>
</div>

{% if text %}
    <div class="row">
        <div class="large-12 columns">
            <div class="panel">
                <h5>Prévisualisation de votre message</h5>
                {{ text|emarkdown }}
            </div>
        </div>
    </div>
{% endif %}

{% endblock %}